language: c
os:
  - linux
  - osx
dist: trusty
sudo: false
compiler:
  - clang
  - gcc
before_install:
# Getting the latest version of "Codacy coverage reporter" often fails.
# Until we figure out why and how to handle it, it's commented out
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install jq ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url) ; fi 
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user gcovr ; fi
script:
  - git clone https://github.com/cgreen-devs/cgreen.git
  - cd cgreen
  - mkdir -p build
  - cd build
  - cmake -DCGREEN_INTERNAL_WITH_GCOV:BOOL=ON ..
  - make -j2
  - cd ../../core
  - make generate_report
  - cd ..
  - make -f posix.mk
  - posix/pubnub_fntest
  - openssl/pubnub_fntest
after_success:
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l c --force-language -r core/coverage.xml ; fi
